snapshot 2025-11-28T12:27:06.687395+00:00

diff --git a/.cirrus.yml b/.cirrus.yml
--- a/.cirrus.yml
+++ b/.cirrus.yml
@@ -3,16 +3,17 @@
 # Main environment vars to set for all tasks
 env:
 
-    FEDORA_NAME: "fedora-38"
-    FEDORA_PRIOR_NAME: "fedora-37"
+    FEDORA_NAME: "fedora-42"
+    FEDORA_PRIOR_NAME: "fedora-41"
 
-    DEBIAN_NAME: "debian-11"
+    DEBIAN_13_NAME: "debian-13"
+    DEBIAN_12_NAME: "debian-12"
+    DEBIAN_11_NAME: "debian-11"
 
-    UBUNTU_DEVEL_NAME: "ubuntu-25.04"
-    UBUNTU_LATEST_NAME: "ubuntu-24.10"
-    UBUNTU_NAME: "ubuntu-24.04"
-    UBUNTU_PRIOR_NAME: "ubuntu-22.04"
-    UBUNTU_PRIOR2_NAME: "ubuntu-20.04"
+    UBUNTU_DEVEL_NAME: "ubuntu-25.10"
+    UBUNTU_LATEST_NAME: "ubuntu-25.04"
+    UBUNTU_2404_NAME: "ubuntu-24.04"
+    UBUNTU_2204_NAME: "ubuntu-22.04"
 
     CENTOS_9_NAME: "centos-stream-9"
 
@@ -25,17 +26,18 @@ env:
 
     # Images exist on GCP already
     CENTOS_9_FAMILY_NAME: "centos-stream-9"
-    DEBIAN_FAMILY_NAME: "debian-11"
-    FEDORA_FAMILY_NAME: "fedora-cloud-38"
-    FEDORA_PRIOR_FAMILY_NAME: "fedora-cloud-37"
+    DEBIAN_13_FAMILY_NAME: "debian-13"
+    DEBIAN_12_FAMILY_NAME: "debian-12"
+    DEBIAN_11_FAMILY_NAME: "debian-11"
+    FEDORA_FAMILY_NAME: "fedora-cloud-42-x86-64"
+    FEDORA_PRIOR_FAMILY_NAME: "fedora-cloud-41-x86-64"
 
-    UBUNTU_DEB_FAMILY_NAME: "ubuntu-minimal-2410-amd64"
-    UBUNTU_LATEST_FAMILY_NAME: "ubuntu-2410-amd64"
-    UBUNTU_FAMILY_NAME: "ubuntu-2404-lts-amd64"
-    UBUNTU_PRIOR_FAMILY_NAME: "ubuntu-2204-lts"
-    UBUNTU_PRIOR2_FAMILY_NAME: "ubuntu-2004-lts"
+    UBUNTU_DEVEL_FAMILY_NAME: "ubuntu-2510-amd64"
+    UBUNTU_DEB_FAMILY_NAME: "ubuntu-minimal-2504-amd64"
+    UBUNTU_LATEST_FAMILY_NAME: "ubuntu-2504-amd64"
     UBUNTU_SNAP_FAMILY_NAME: "ubuntu-2404-lts-amd64"
-    UBUNTU_DEVEL_FAMILY_NAME: "ubuntu-2504-amd64"
+    UBUNTU_2404_FAMILY_NAME: "ubuntu-2404-lts-amd64"
+    UBUNTU_2204_FAMILY_NAME: "ubuntu-2204-lts"
 
     # Curl-command prefix for downloading task artifacts, simply add the
     # the url-encoded task name, artifact name, and path as a suffix.
@@ -106,17 +108,19 @@ rpm_build_task:
             PROJECT: ${CENTOS_PROJECT}
             BUILD_NAME: ${CENTOS_9_NAME}
             VM_FAMILY_NAME: ${CENTOS_9_FAMILY_NAME}
-        - env: &fedora
-            PROJECT: ${FEDORA_PROJECT}
-            BUILD_NAME: ${FEDORA_NAME}
-            VM_FAMILY_NAME: ${FEDORA_FAMILY_NAME}
-        - env: &fedoraprior
-            PROJECT: ${FEDORA_PROJECT}
-            BUILD_NAME: ${FEDORA_PRIOR_NAME}
-            VM_FAMILY_NAME: ${FEDORA_PRIOR_FAMILY_NAME}
+#        - env: &fedora
+#            PROJECT: ${FEDORA_PROJECT}
+#            BUILD_NAME: ${FEDORA_NAME}
+#            VM_FAMILY_NAME: ${FEDORA_FAMILY_NAME}
+#        - env: &fedoraprior
+#            PROJECT: ${FEDORA_PROJECT}
+#            BUILD_NAME: ${FEDORA_PRIOR_NAME}
+#            VM_FAMILY_NAME: ${FEDORA_PRIOR_FAMILY_NAME}
     setup_script: |
         dnf clean all
-        dnf -y install rpm-build rpmdevtools gettext python3-devel
+        dnf -y install rpm-build rpmdevtools gettext python3-devel python3-pexpect python3-pyyaml
+        dnf -y install python3-wheel || true
+    # dnf failures above ignored for distros that do not yet have python3-wheel, e.g. CS 9
     main_script: |
         mkdir -p /rpmbuild/{BUILD,BUILDROOT,RPMS,SRPMS,SOURCES}
         python3 setup.py sdist
@@ -135,22 +139,41 @@ rpm_build_task:
 deb_build_task:
     skip: *man-changes-include
     alias: "deb_build"
-    name: "deb Build From Checkout"
+    name: "deb Build From Checkout - ${BUILD_NAME}"
     gce_instance:
-        image_project: "${UBUNTU_PROJECT}"
-        image_family: "${UBUNTU_DEB_FAMILY_NAME}"
+        image_project: "${PROJECT}"
+        image_family: "${VM_FAMILY_NAME}"
         type: e2-medium
+    matrix:
+        - env: &debian-11-deb-pkg
+            PROJECT: ${DEBIAN_PROJECT}
+            BUILD_NAME: ${DEBIAN_11_NAME}
+            VM_FAMILY_NAME: ${DEBIAN_11_FAMILY_NAME}
+        - env: &debian-12-deb-pkg
+            PROJECT: ${DEBIAN_PROJECT}
+            BUILD_NAME: ${DEBIAN_12_NAME}
+            VM_FAMILY_NAME: ${DEBIAN_12_FAMILY_NAME}
+        - env: &debian-13-deb-pkg
+            PROJECT: ${DEBIAN_PROJECT}
+            BUILD_NAME: ${DEBIAN_13_NAME}
+            VM_FAMILY_NAME: ${DEBIAN_13_FAMILY_NAME}
+        - env: &ubuntu-latest-deb-pkg
+            PROJECT: ${UBUNTU_PROJECT}
+            BUILD_NAME: ${UBUNTU_LATEST_NAME}
+            VM_FAMILY_NAME: ${UBUNTU_DEB_FAMILY_NAME}
     setup_script: |
+        [[ ${BUILD_NAME} == "${DEBIAN_11_NAME}" ]] && sudo sed -i '/-backports/ s/^/#/' /etc/apt/sources.list
         apt update --allow-releaseinfo-change
         apt -y install devscripts equivs python3-pip
         mk-build-deps
-        apt -y install ./sosreport-build-deps*.deb
-        pip3 install -r test-requirements.txt --break-system-packages
+        apt -y install ./sos-build-deps*.deb
+        [[ $(pip3 install --help | grep break-system) ]] && PIP_EXTRA="--break-system-packages"
+        pip3 install -r test-requirements.txt ${PIP_EXTRA}
     main_script: |
         dpkg-buildpackage -b -us -uc -rfakeroot -m --build-by="noreply@canonical.com"
-    prep_artifacts_script: mv ../*.deb ./sos_cirrus.deb
+    prep_artifacts_script: mv ../*.deb ./sos_${BUILD_NAME}.deb
     packages_artifacts:
-        path: ./sos_cirrus.deb
+        path: ./sos_${BUILD_NAME}.deb
         type: application/octet-stream
 
 # Make sure a user can manually build a snap from the checkout
@@ -190,48 +213,60 @@ report_stageone_task:
     gce_instance: *standardvm
     matrix:
         - env: *centos9
-        - env: *fedora
-        - env: *fedoraprior
-        - env: &ubuntu
+#        - env: *fedora
+#        - env: *fedoraprior
+        - env: &ubuntu-2404
             PKG: "snap"
             PROJECT: ${UBUNTU_PROJECT}
-            BUILD_NAME: "${UBUNTU_NAME} - ${PKG}"
-            VM_FAMILY_NAME: ${UBUNTU_FAMILY_NAME}
-        - env: &ubuntuprior
+            BUILD_NAME: "${UBUNTU_2404_NAME} - ${PKG}"
+            VM_FAMILY_NAME: ${UBUNTU_2404_FAMILY_NAME}
+        - env: &ubuntu-2204
             PKG: "snap"
             PROJECT: ${UBUNTU_PROJECT}
-            BUILD_NAME: "${UBUNTU_PRIOR_NAME} - ${PKG}"
-            VM_FAMILY_NAME: ${UBUNTU_PRIOR_FAMILY_NAME}
-        - env: &ubuntuprior2
-            PKG: "snap"
-            PROJECT: ${UBUNTU_PROJECT}
-            BUILD_NAME: "${UBUNTU_PRIOR2_NAME} - ${PKG}"
-            VM_FAMILY_NAME: ${UBUNTU_PRIOR2_FAMILY_NAME}
+            BUILD_NAME: "${UBUNTU_2204_NAME} - ${PKG}"
+            VM_FAMILY_NAME: ${UBUNTU_2204_FAMILY_NAME}
         - env: &ubuntu-latest-snap
             PKG: "snap"
             PROJECT: ${UBUNTU_PROJECT}
             BUILD_NAME: "${UBUNTU_LATEST_NAME} - ${PKG}"
             VM_FAMILY_NAME: ${UBUNTU_LATEST_FAMILY_NAME}
         - env: &ubuntu-latest-deb
+            <<: *ubuntu-latest-deb-pkg
             PKG: "deb"
-            PROJECT: ${UBUNTU_PROJECT}
             BUILD_NAME: "${UBUNTU_LATEST_NAME} - ${PKG}"
+            DEB_BUILD_NAME: ${UBUNTU_LATEST_NAME}
             VM_FAMILY_NAME: ${UBUNTU_LATEST_FAMILY_NAME}
+        - env: &debian-13
+            <<: *debian-13-deb-pkg
+            PKG: "deb"
+            DEB_BUILD_NAME: ${BUILD_NAME}
+        - env: &debian-12
+            <<: *debian-12-deb-pkg
+            PKG: "deb"
+            DEB_BUILD_NAME: ${BUILD_NAME}
+        - env: &debian-11
+            <<: *debian-11-deb-pkg
+            PKG: "deb"
+            DEB_BUILD_NAME: ${BUILD_NAME}
     setup_script: &setup |
         if [ $(command -v apt) ]; then
-            apt -y purge sosreport
+            [[ ${BUILD_NAME} == "${DEBIAN_11_NAME}" ]] && sudo sed -i '/-backports/ s/^/#/' /etc/apt/sources.list
+            [[ "$(dpkg -l sos)" ]] && apt -y purge sos ubuntu-server
+            [[ "$(dpkg -l sosreport)" ]] && apt -y purge sosreport ubuntu-server
             apt update --allow-releaseinfo-change
-            apt -y install python3-pip snapd
+            apt -y install python3-pip ethtool python3-systemd
             if [ ${PKG} == "snap" ] ; then
+                apt -y install snapd
                 echo "$ARTCURL/snap%20Build%20From%20Checkout/packages/sosreport_test_amd64.snap"
                 $ARTCURL/snap%20Build%20From%20Checkout/packages/sosreport_test_amd64.snap
                 systemctl start snapd
                 snap install ./sosreport_test_amd64.snap --classic --dangerous
                 snap alias sosreport.sos sos
             elif [ ${PKG} == "deb" ]; then
-                echo "$ARTCURL/deb%20Build%20From%20Checkout/packages/sos_cirrus.deb"
-                $ARTCURL/deb%20Build%20From%20Checkout/packages/sos_cirrus.deb
-                apt -y install ./sos_cirrus.deb
+                echo "$ARTCURL/deb%20Build%20From%20Checkout%20-%20${DEB_BUILD_NAME}/packages/sos_${DEB_BUILD_NAME}.deb"
+                $ARTCURL/deb%20Build%20From%20Checkout%20-%20${DEB_BUILD_NAME}/packages/sos_${DEB_BUILD_NAME}.deb
+                apt -y install ./sos_${DEB_BUILD_NAME}.deb
+                sed -i 's/\(127.0.1.1\)/#\1/g' /etc/hosts
             fi
         fi
         if [ $(command -v dnf) ]; then
@@ -286,10 +321,11 @@ report_stagetwo_task:
     gce_instance: *standardvm
     matrix:
         - env: *centos9
-        - env: *fedora
-        - env: *ubuntu
+#        - env: *fedora
+        - env: *ubuntu-2404
         - env: *ubuntu-latest-snap
         - env: *ubuntu-latest-deb
+        - env: *debian-13
     setup_script: *setup
     install_pexpect_script: |
         if [ $(command -v apt) ]; then
@@ -325,15 +361,16 @@ report_foreman_task:
     alias: "foreman_integration"
     name: "Integration Test - Foreman ${FOREMAN_VER} - ${BUILD_NAME}"
     depends_on: stageone_report
+    environment:
+      FOREMAN_VER: "3.15"
+      KATELLO_VER: "4.17"
     gce_instance: &bigvm
         <<: *standardvm
-        type: e2-standard-2
+        type: e2-highmem-4
     matrix:
-        - env:
-            PROJECT: ${DEBIAN_PROJECT}
-            VM_FAMILY_NAME: ${DEBIAN_FAMILY_NAME}
-            BUILD_NAME: ${DEBIAN_NAME}
-            FOREMAN_VER: "3.7"
+        - env: *centos9
+        - env: *debian-12
+        - env: *ubuntu-2204
     setup_script: *setup
     foreman_setup_script: ./tests/test_data/foreman_setup.sh
     main_script: PYTHONPATH=tests/ avocado run -p TESTLOCAL=true --max-parallel-tasks=1 -t foreman tests/product_tests/foreman/
